### ISSUE TITLE
Trailing comments are deleted

### ISSUE THREAD

**Issue by KristofferC** [domluna/JLFmt.jl#4]
```
julia> format("foo #bar"; indent_width=4, max_width=80)
"foo"
```

**Comment by domluna** [comment]
Yep - https://github.com/domluna/JLFmt#known-limitations

**Comment by KristofferC** [comment]
Sorry, should have read that first. Feel free to close.

**Comment by domluna** [comment]
Still an issue nonetheless 😄

**Comment by domluna** [comment]
Aside from the caveat mentioned in the Readme inline comments work now so clossingg this
