### ISSUE TITLE
Formatting for many args

### ISSUE THREAD

**Issue by SimonDanisch** [domluna/JLFmt.jl#9]
Would be nice to get functions with lots of arguments be reformatted to look like:
```julia
function longfunctionname_that_is_long(
        lots, 
        of, 
        args,
        even, 
        more, 
        args
    )
    ..code..
end
```
Instead of:
```julia
function longfunctionname_that_is_long(lots, of, args,
                                       even, more, args)
    ..code..
end
```

Same applies for function calls, keyword arguments etc!

**Comment by domluna** [comment]
pinning https://github.com/JuliaGeometry/TetGen.jl/blob/master/src/cppwrapper.jl#L198-L216 for an example.

**Comment by domluna** [comment]
@SimonDanisch would you agree if that function definition, etc exceeds the line length to nest it like above?

I think actual function calls should probably remain as

```
foo(a,
    b,
    c)
```

Instead of

```
foo(
    a,
    b,
    c
)
```

what do you think?

Also how should the args be indented in the function def?

**Comment by domluna** [comment]
How's this https://gist.github.com/domluna/d381483879eb287e1e0a6fb3cf13f5ec?

**Comment by SimonDanisch** [comment]
Sorry, I first was on vacation and then I got side tracked while commenting :D This looks great :) 

Although, I usually try to make this:
```julia
dict = Dict{Symbol,Any}(
        :numberofpointattributes => NAttributes,
        :numberofpointmtrs => NMTr,
        :numberofcorners => NSimplex,
        :firstnumber => Cint(1),
        :mesh_dim => Cint(3),
    )
```
Like this:
```julia
dict = Dict{Symbol,Any}(
    :numberofpointattributes => NAttributes,
    :numberofpointmtrs => NMTr,
    :numberofcorners => NSimplex,
    :firstnumber => Cint(1),
    :mesh_dim => Cint(3),
)
```
Since the closing bracket still seems to clearly belong to `dict` and it wastes less space ;)

**Comment by BeastyBlacksmith** [comment]
But the former plays nicer with Junos  indent based block recognition

**Comment by domluna** [comment]
With #14 this is (assuming indent width is 4)

```
function longfunctionname_that_is_long(
    lots, 
    of, 
    args,
    even, 
    more, 
    args
)
    ..code..
end
```

and

```
dict = Dict{Symbol,Any}(
    :numberofpointattributes => NAttributes,
    :numberofpointmtrs => NMTr,
    :numberofcorners => NSimplex,
    :firstnumber => Cint(1),
    :mesh_dim => Cint(3),
)
```
